on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: franzbischoff/replace_envs@v1
        env:
          CONFLUENT_KSQLDB_ENDPOINT: 'https://pksqlc-x6x81.westeurope.azure.confluent.cloud:443'
          CONFLUENT_KSQLDB_API_KEY: 'NFDRQUQXXDKLH6BL'
          CONFLUENT_KSQLDB_API_SECRET: '74DNWNtwpnFhikzwLpqMDO1QimyIU+nWHroZtWjOVFLog1myGn4w45tJ+csaQw3T'
        with:
          from_file: 'ksql-migrations.properties'
          to_file: 'ksql-migrations.properties'
          commit: 'false'
      - uses: ./.github/actions/ksqldb-migrations-validate
      - uses: ./.github/actions/ksqldb-migrations-apply
